### ISSUE TITLE
connection error

### ISSUE THREAD

**Issue by YahiaAgwa** [soernt/signalr_client#1]
hello everyone

when i call the start function
if (hubConnection.state != HubConnectionState.Connected) {
      await hubConnection.start();
    }
i get this issue

I/flutter (22035): FINER: 2018-11-16 19:57:32.684732: Starting HubConnection.
I/flutter (22035): FINER: 2018-11-16 19:57:32.712285: Starting connection with transfer format 'TransferFormat.Text'.
I/flutter (22035): FINER: 2018-11-16 19:57:32.727879: Sending negotiation request: http://192.168.2.1:52001/PrivateChat/negotiate
I/flutter (22035): FINEST: 2018-11-16 19:57:32.800175: HTTP send: url 'http://192.168.2.1:52001/PrivateChat/negotiate', method: 'POST' content: ''
Syncing files to device SM G532F...
I/flutter (22035): SEVERE: 2018-11-16 19:57:33.603061: Failed to complete negotiation with the server: Invalid argument(s): Response Content-Type not supported: [application/json; charset=UTF-8]
I/flutter (22035): SEVERE: 2018-11-16 19:57:33.603902: Failed to start the connection >> : Invalid argument(s): Response Content-Type not supported: [application/json; charset=UTF-8]
E/flutter (22035): [ERROR:flutter/shell/common/shell.cc(184)] Dart Error: Unhandled exception:
E/flutter (22035): Invalid argument(s): Response Content-Type not supported: [application/json; charset=UTF-8]
E/flutter (22035): #0      HttpConnection._startInternal (package:signalr_client/http_connection.dart:257:7)
E/flutter (22035): <asynchronous suspension>
E/flutter (22035): #1      HttpConnection.start (package:signalr_client/http_connection.dart:142:21)
E/flutter (22035): #2      HubConnection.start (package:signalr_client/hub_connection.dart:103:23)
E/flutter (22035): <asynchronous suspension>
E/flutter (22035): #3      ChatService.onCreate (package:mbrcld/services/chatService.dart:38:27)
E/flutter (22035): <asynchronous suspension>
E/flutter (22035): #4      main (package:mbrcld/main.dart:103:21)
E/flutter (22035): <asynchronous suspension>
E/flutter (22035): #5      _startIsolate.<anonymous closure> (dart:isolate/runtime/libisolate_patch.dart:289:19)
E/flutter (22035): #6      _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:171:12)

**Comment by puffmonkey** [comment]
Hi,

I've experienced the same error message, and found that it is because the Hub you're connecting to is returning the content-type: [application/json; charset=UTF-8]. I still haven't found a solution to this issue. @YahiaAgwa Have you been able to get any further with this issue?

**Comment by puffmonkey** [comment]
A temporary solution I found to work was to edit the DartIOHttpClient such that the .indexOf("application/json") (on line: 87) (is .indexOf("application/json; charset=UTF-8") instead.
I do bump into another problem after doing this, and that is with the NegotiationResponse, which I still cannot seem to find a way around. Let me know if this temporary fix solves your problem.

**Comment by soernt** [comment]
Hi there,

this all looks like you are using not ASP.net Core - right? This library is for .net Core only, since Microsoft implements a [different](https://docs.microsoft.com/en-us/aspnet/core/signalr/version-differences?view=aspnetcore-2.2) hub protocol at .net Core.

Kind regards,
Sörnt

**Comment by puffmonkey** [comment]
Yes, you're right. It is because there is a difference between the implementation of ASP.net Core MVC SignalR and ASP.net MVC SignalR. Thank you for clearing that up for me. Would you recommend a migration over to ASP.net Core from ASP.net? I am trying to build a mobile and web application that supports real time communication.

**Comment by soernt** [comment]
That depends on your requirements. First check if all your required components have a .net core compatible version. If so, than I would switch over to .net Core.

**Comment by AymanMubark** [comment]
can  build using ASP.net MVC SignalR not core ??
