### ISSUE TITLE
How can send data into server using signalr_client   flutter

### ISSUE THREAD

**Issue by Adilkp796** [soernt/signalr_client#2]
I need send data to server either headers or query string ....

**Comment by Adilkp796** [comment]
I need send data to server either headers or query string ....

**Comment by Adilkp796** [comment]
Thanks for your support @soernt .Finally I resolve my issue by passing query string like this `http:192.168.0.100/Chat?tmz=330`. And i get by calling `context.Request.Query["tmz"]`.

**Comment by soernt** [comment]
aha - Ok, I thought you need to pass also the chat data via headers/query string.
