### ISSUE TITLE
Not able to specify Hub in server. 

### ISSUE THREAD

**Issue by ghost** [soernt/signalr_client#21]
For example in one of our API's we have multiple signalR hubs such as UserHub, DataHub, and Message Hub. In C# we would do something like:

` var signalRConnection = new HubConnection("http://{serverUrl}");
  var signalRUserProxy = signalRConnection.CreateHubProxy("UserHub");
  var signalRDataProxy = signalRConnection.CreateHubProxy("DataHub");
  var signalRMessageProxy = signalRConnection.CreateHubProxy("MessageHub");
  signalRConnection.Start().Wait();
  signalRUserProxy.On("updateUsers", x => UpdateUsers(x));
  signalRDataProxy.On("updateData", x => UpdateData(x));
  signalRMessageProxy.On("updateMessages", x => UpdateMessages(x));`

Where each proxy represents a different Hub. I don't see how to accomplish this with the example code supplied.

**Comment by soernt** [comment]
That is not [possible](https://docs.microsoft.com/en-us/aspnet/core/signalr/version-differences?view=aspnetcore-2.2#single-hub-per-connection) anymore with ASP.Net Core.
You need to have a dedicated connection foreach hub.
