### ISSUE TITLE
Dose't support asp.net mvc  

### ISSUE THREAD

**Issue by AymanMubark** [soernt/signalr_client#30]
I have a project with asp.net MVC, not core and i have this error
Response Content-Type not supported: [application/json; charset=UTF-8]

**Comment by lionelquirynen** [comment]
A Flutter SignalR Client for ASP.NET Core, so it's not compatible with asp.net

**Comment by AymanMubark** [comment]
when can be compatible 😅or what can I do

**Comment by lionelquirynen** [comment]
either write your own plugin, or port your project from asp.net to asp.net core

**Comment by AymanMubark** [comment]
oh thanks

**Comment by davbaron** [comment]
@AymanMubark , I had the same problem - my web api solution was standard .net framework... but I needed SignalR, so I ported/converted my solution to .net core. Yes, there are a few things that were broken, but if you go thru the issues one by one, it was not that bad.
