### ISSUE TITLE
How to pass complex object as parameter

### ISSUE THREAD

**Issue by sherifhasan** [soernt/signalr_client#5]
The following code throws `Converting object to an encodable object failed: Instance of 'InvocationMessage'`

```
_hubConnection.invoke("Broadcast", args: [request, broadMessage]);
```

I already implemented `toJson()` as per instruction 
`use objects that implements toJson() since that method is used by the dart:convert package to serialize an object.` here https://pub.dartlang.org/packages/signalr_client

```
class NotificationRequest {
  int connectionType;
  String command;
  int userId;
  String userName;
  String uuid;

  NotificationRequest(
      {this.command,
      this.connectionType,
      this.userId,
      this.userName,
      this.uuid});

  Map<String, dynamic> toJson() => {
        'connectionType': connectionType,
        'command': command,
        'userId': userId,
        'userName': userName,
        'uuid': uuid
      };
}
```

```
class BroadCastMessage {
  String message;
  BroadCastMessage({this.message});
  Map<String, dynamic> toJson() => {'message': message};
}
```

**Comment by soernt** [comment]
This should be fixed within the new version 0.1.5.
Thank you for reporting the bug!
There is a [test](https://github.com/soernt/signalr_client/blob/master/testapp/client/lib/tests/clientInvoke/clientMethodComplexParameterComplesReturnValue.dart) for this.
