### ISSUE TITLE
Unable to initialize any of the available transports.

### ISSUE THREAD

**Issue by samjunction** [soernt/signalr_client#8]
When trying to connect I am getting Unable to initialize any of the available transports. error message. My signalr server is using Microsoft.AspNet.SignalR.  I tried connecting to server using javascript signalr library and it worked fine. 

Please help.

**Comment by soernt** [comment]
Hello,

this library is only for SignalR while using Asp.Net Core. The hub protocol between .Net and .Net Core is [different](https://docs.microsoft.com/en-us/aspnet/core/signalr/version-differences?view=aspnetcore-2.2).

Kind regards,
- Sörnt
